# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-17 15:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('layout_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='layout_images')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('classes', models.ManyToManyField(to='app.Class')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('classes', models.ManyToManyField(to='app.Class')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('layout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Layout')),
                ('zone_name', models.CharField(choices=[('A', 'Zone A'), ('B', 'Zone B'), ('C', 'Zone C'), ('D', 'Zone D')], max_length=2)),
                ('users', models.ManyToManyField(to='app.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='layout',
            name='class_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Class'),
        ),
        migrations.AddField(
            model_name='layout',
            name='place_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Place'),
        ),
    ]
