# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-10 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClassMateZ', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('class_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ClassMateZ.Class')),
                ('place_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='ClassMateZ.Place')),
                ('image', models.ImageField(upload_to='layout_images')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='classes',
            field=models.ManyToManyField(to='ClassMateZ.Class'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='classes',
            field=models.ManyToManyField(to='ClassMateZ.Class'),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('layout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ClassMateZ.Layout')),
                ('zone_name', models.CharField(choices=[('A', 'Zone A'), ('B', 'Zone B'), ('C', 'Zone C'), ('D', 'Zone D')], max_length=2, primary_key=True)),
                ('users', models.ManyToManyField(to='ClassMateZ.UserProfile')),
            ],
        ),
    ]
