# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-10 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClassMateZ', '0002_auto_20170310_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='layout_id',
            field=models.AutoField(default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='layout',
            name='class_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ClassMateZ.Class'),
        ),
        migrations.AlterField(
            model_name='layout',
            name='place_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ClassMateZ.Place'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='zone_name',
            field=models.CharField(choices=[('A', 'Zone A'), ('B', 'Zone B'), ('C', 'Zone C'), ('D', 'Zone D')], max_length=2),
        ),
    ]
